[package]
name = "webapp"
version = "0.1.0"
edition = "2018"


[dependencies.bindb]
version = "0.0.3"
path = "../bindb"

[dependencies.rpmrepo]
version = "0.0.3"
path = "../repo"

[dependencies.cache]
path = "../cache"

[dependencies]